name: "Checkout repo With SSH"
description: "Checkout repo With SSH"

inputs:
  repo_owner:
    description: "The Owner of repo"
    required: true
  repo_name:
    description: "The Name of repo"
    required: true
  git_private_key:
    description: "The Private Key of Git"
    required: true

runs:
  using: "composite"
  steps:
      - name: Checkout a repo With SSH
        env:
          ACTION_KEY: ${{ inputs.git_private_key }}
        run: |
          mkdir -p ~/.ssh/
          echo "$ACTION_KEY" > ~/.ssh/id_rsa
          chmod 700 ~/.ssh
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Action"
          git clone git@github.com:${{inputs.repo_owner}}/${{inputs.repo_name}}.git
          git submodule init
          git submodule update --remote
