name: "Checkout repo With SSH"
description: "Checkout repo With SSH"

inputs:
  git_private_key:
    description: "The Private Key of Git"
    required: true
  repo:
    description: "The name of repo"
    default: "${{ github.repository }}"
  shell: 
    description: "Define the shell to run command. Default: bash"
    default: 'bash'
  branch: 
    description: "Define the branch to update. Default: main"
    default: 'main'

runs:
  using: "composite"
  steps:
  - name: Checkout a repo With SSH On Linux/Unix/MacOS
    if: runner.os != 'Windows'
    shell: ${{ inputs.shell }}
    env:
      ACTION_KEY: ${{ inputs.git_private_key }}
    run: |
      mkdir -p ~/.ssh/
      echo "$ACTION_KEY" > ~/.ssh/id_rsa
      chmod 700 ~/.ssh
      chmod 600 ~/.ssh/id_rsa
      ssh-keyscan github.com >> ~/.ssh/known_hosts
      git config --global user.email "actions@github.com"
      git config --global user.name "GitHub Action"
      git clone git@github.com:${{ inputs.repo }}.git ./
      if [ -f ".gitmodules" ]; then
        echo "update sub git repo"
        git submodule init
        git submodule update --remote
      fi
      git checkout ${{ inputs.branch }}

  - name: Checkout a repo With SSH On Windows
    if: runner.os == 'Windows'
    shell: ${{ inputs.shell }}
    env:
      ACTION_KEY: ${{ inputs.git_private_key }}
    run: |
      Write-Output "$profile"

